(pillan) cnpg backup bump to v0.3
lsst-it/k8s-cookbook pull request #173
Opened 2023-05-24 21:30 UTC by cbarria

cloudnativepg backups needed an update in the TTS because the amounts of files were not been erased past 60 days.

2023-05-24 21:33 UTC, jhoblitt requested changes

2023-05-24 21:45 UTC, cbarria commented on pillan/cnpg/cnpg-backup.sh
> +            image: docker.io/cbarria/cnpg-backup:0.3
yes, absolutely, going to set this as a WIP and will move everything when i get back.

2023-05-24 21:47 UTC, cbarria commented on pillan/cnpg/cnpg-backup.sh
> +              mountPath: "/tmp"
yes, just until they are compressed and shipped to the s3, then the storage dies.

2023-06-06 15:55 UTC, jhoblitt approved these changes
LGTM.

2023-06-08 13:41 UTC, merged