(fleet/dashboards) fix snmp dashboars
lsst-it/k8s-cookbook pull request #387
Opened 2024-05-10 16:50 UTC by fbegyn

The grafana dashboards are using specific datasources in the first design. This causes the UUID to break when importing these through provisioning files into other grafana instances. The fix for this is to use a datasource variable.

2024-05-10 17:27 UTC, jhoblitt requested changes
Comments including screenshots are in this thread on slack: https://lsstc.slack.com/archives/C05JLDDAPAR/p1715360161601749

2024-05-10 23:19 UTC, jhoblitt commented
The commit message also contains a typo: "dashboars"

2024-05-14 17:00 UTC, fbegyn commented
I've cleaned up a lot of dashboards to bring them back into working state I believe. The only 2 broken parts are the `PDU montoring` and `Base to summit temporary`. I'd prefer to get this PR merged in the current state, further tweaks to those 2 and other dashboards (improving network overview) can be done in subsequent PRs.

2024-05-28 17:00 UTC, jhoblitt commented on fleet/lib/grafana-dashboards/dashboards/hosts-overview.json
The `mds_hosts` and `rgw_hosts` drop downs don't have any values.

![image](https://github.com/lsst-it/k8s-cookbook/assets/948901/64fe0dbc-8758-4fec-b424-b1f8990794a0)

2024-05-28 17:07 UTC, jhoblitt commented on fleet/lib/grafana-dashboards/dashboards/osd-device-details.json
The physical device metrics aren't working for me on ruka and I don't understand why.  The metrics are present in prometheus. 
![image](https://github.com/lsst-it/k8s-cookbook/assets/948901/d4a12d75-5695-477c-946f-d20d8a01af85)
![image](https://github.com/lsst-it/k8s-cookbook/assets/948901/e3ee6406-5d88-40ea-a033-0884afb953d4)

2024-05-28 17:10 UTC, jhoblitt commented on fleet/lib/grafana-dashboards/dashboards/osds-overview.json
I have to scale the fontsizes way down to get remove horizontal scroll bars from the latency tables.

![image](https://github.com/lsst-it/k8s-cookbook/assets/948901/369a9e80-b9b4-44f8-b6d8-60faece41e82)

At 60% the values become visible:

![image](https://github.com/lsst-it/k8s-cookbook/assets/948901/661bac11-436a-44b6-b549-f7506b462454)

2024-05-29 23:43 UTC, jhoblitt requested changes
I have completed inspect all dashboard within this PR and made comments where I have concerns. WRT the Ceph dashboards.  If the titles are direct copies of upstream dashboards, I think its OK to not rename them to have "Ceph" in the title but I think they need to be in a Ceph (or Rook) folder to logically group them together.

2024-05-29 23:43 UTC, jhoblitt commented on fleet/lib/grafana-dashboards/dashboards/pool-overview.json
The pool overview table is is hard to use.  There are a lot of columns of duplicated or unimportant data that can be removed. The important information is on the right side of the table.  The vertical height should be increased as we have a few clusters with a fair number of pools.

![image](https://github.com/lsst-it/k8s-cookbook/assets/948901/43ecc2c4-72db-439a-b9e4-731caf098157)

2024-05-29 23:43 UTC, jhoblitt commented on fleet/lib/grafana-dashboards/dashboards/radosgw-detail.json
This dashboard appears to be broken on both ruka and ayekan.

![image](https://github.com/lsst-it/k8s-cookbook/assets/948901/d1d19b4b-cc86-4d4c-b79b-3ceac202e611)

2024-05-29 23:43 UTC, jhoblitt commented on fleet/lib/grafana-dashboards/dashboards/radosgw-overview.json
This dashboard seems to be broken on ruka and ayekan for all clusters.

![image](https://github.com/lsst-it/k8s-cookbook/assets/948901/ec1e944c-a677-483e-888f-0dd30f2c07d5)

2024-05-29 23:43 UTC, jhoblitt commented on fleet/lib/grafana-dashboards/dashboards/radosgw-sync-overview.json
We don't currently have rgw zone replication enabled on any cluster. We have tested it in the past and will probably use it later this year.  It currently isn't possible to test with dashboard.

2024-05-29 23:43 UTC, jhoblitt commented on fleet/lib/grafana-dashboards/dashboards/rbd-details.json
This dashboard seems to be broken on both ruka and ayekan.

![image](https://github.com/lsst-it/k8s-cookbook/assets/948901/7fddff5c-3d4e-46d2-9d31-6821eea9316d)

2024-05-29 23:43 UTC, jhoblitt commented on fleet/lib/grafana-dashboards/dashboards/rbd-overview.json
The tables on this dashboard are difficult to read with my browser fonts at 100%.  I have to scale it down to 60% to get all the data to render without horizontal scroll bars.

100%:
![image](https://github.com/lsst-it/k8s-cookbook/assets/948901/f316e133-bde6-4a0e-ac5f-eafe2e874947)

60%:
![image](https://github.com/lsst-it/k8s-cookbook/assets/948901/2da13336-74ac-497a-a7cd-fd10815dab52)

2024-05-29 23:43 UTC, jhoblitt commented on fleet/lib/grafana-dashboards/dashboards/rgw-s3-analytics.json
This dashboard seems to be broken on both ruka and ayekan for all cluster / rgw_server combos I tried.

![image](https://github.com/lsst-it/k8s-cookbook/assets/948901/c54992a3-8e98-47ec-976d-d711edc8a436)

2024-05-29 23:43 UTC, jhoblitt commented on fleet/lib/grafana-dashboards/dashboards/rook-ceph.json
Is this dashboard a duplicate of `Ceph - Cluster`?  It does not support multiple clusters.

![image](https://github.com/lsst-it/k8s-cookbook/assets/948901/e3d3bb73-e60b-479f-9f0b-3005d20fe17a)

2024-08-30 22:45 UTC, jhoblitt commented
@KrisBuytaert @fbegyn What is the status of this PR?  Is it ready for re-review?

2024-10-25 21:50 UTC, jhoblitt commented
I'm going to go ahead and merge this as-is. Any remaining issues will be addressed in new PRs.

2024-10-25 21:50 UTC, merged