(fleet/opensearch/logging) Opensearch logging cluster config
lsst-it/k8s-cookbook pull request #397
Opened 2024-05-14 16:55 UTC by fbegyn

This handles the config and setup of the opensearch cluster used for logs. 

Pre sets up:
* self-signed certificates for cluster with auto-renewal (opensearch-operator only provided 1y)
* securityconfig definition for opensearch (defines users, roles, mappings, tenants, config, ...)
* external secrets for keycloak and the admin users

Opensearch-logging:
* provides the `opensearchcluster` config
* sets up ISM policies and index templates.

2024-05-15 00:24 UTC, jhoblitt reviewed
I am still working on testing this PR.  More comments will likely follow tomorrow.

2024-05-16 08:50 UTC, fbegyn commented on fleet/lib/fluentbit/manifests/daemonset-kube.yaml
While I understand the apprehensiveness, the upstream config does not allow the flexibility of having both daemonset and deployment use shared parts of the configuration (unless you manually start defining these and then we're back here). Doing these in manifests, allows for much finer control of shared configs and resources.

When switching back to the helm charts, we'd need to deploy 2 helm charts with partially duplicated configs for both, pin the helm versions (in essence also pinning the application version) and still keep track if configuration changes upstream won't break things.

I'm willing to port these back into the helm chart configs if that's a hard requirement, but this would take time away from other parts of the project at this stage.

2024-05-16 08:50 UTC, fbegyn commented on fleet/lib/fluentbit/manifests/daemonset-kube.yaml
> +        image: fluent/fluent-bit:3.0
done

2024-05-16 08:51 UTC, fbegyn commented on fleet/lib/opensearch-logging-pre/fleet.yaml
> +targetCustomizations:
removed it, was keeping it in case in the future any customization is required. But it can be added at a later stage.

2024-05-17 03:24 UTC, jhoblitt reviewed
I have not been unable to get opensearch working on ruka.  Login via keycloak is working but the indexes don't seem to be loading.  There's no errors in the operator log even with `--loglevel=debug` set and the various CRs are all present in the cluster. E.g.
```
$ k get OpensearchIndexTemplate
NAME            AGE
logs            2d3h
logs-firewall   2d3h
```

The custom tenant list is populated but under all custom tenants and the "Global" tenant, no indexes are visible.

![image](https://github.com/lsst-it/k8s-cookbook/assets/948901/6c754e97-783a-446f-a89c-b19aec20ec06)
![image](https://github.com/lsst-it/k8s-cookbook/assets/948901/45d3284c-ac71-4536-9358-a513ea409081)

2024-05-17 08:07 UTC, fbegyn commented on fleet/lib/opensearch-logging/clusters/logging.yaml
> +    version: &os_version 2.11.0
This has been an oversight for me, upgrading to 2.11.1 is no problem. 2.12 and above have a bug in the dashboarding that breaks openid/keycloak logins.

See:
https://github.com/opensearch-project/security-dashboards-plugin/issues/926#issuecomment-2090126352
https://github.com/opensearch-project/security-dashboards-plugin/pull/1899

2024-05-29 23:50 UTC, jhoblitt requested changes
Also, 2c1953b3c2db0c19a2be9521747fb30e96eacee5 should be updated to have a useful commit message before this is ready for merge.

2024-05-29 23:59 UTC, jhoblitt requested changes
I retested this PR on ruka today and the results were the same.  I am able to get as far as logging in via keycloak, I'm able to switch tenets, but there are no indexes.  I am going to need to assistance to be able to deploy / review this work. 

Is manual configuration required to get opensearch working?  If so, could we add instructions to this PR as well?

2024-06-17 08:55 UTC, fbegyn commented on fleet/lib/opensearch-logging/clusters/logging.yaml
> +      # TLS here for the HTTP API
This is probably some config drift, will clean up.

2024-06-17 14:12 UTC, fbegyn commented on fleet/lib/fluentbit/manifests/daemonset-kube.yaml
I took another stab at using the fluent-operator in https://github.com/lsst-it/k8s-cookbook/tree/fluent-operator-deploy

The operator certainly allows for the flexibility we require, but falls flat on it's face due the operator itself not fully being ready too handle namespace in the correct way. It makes a lot of assumption for cluster wide deployments. I'm sure the operator can be configured and used correctly here, but IMHO the documentation is severely lacking.

Another approach has been tried in https://github.com/lsst-it/k8s-cookbook/tree/fluentbit-helm which seems to work. My proposal would be to split out the fluentbit config from the PR (totally my fault that it creeped in) and switch to the helm based deployment of fluentbit.

2024-08-21 14:21 UTC, fbegyn commented on fleet/lib/opensearch-logging/overlays/ayekan/ingress.yaml
> +    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
Personally I'd think that having the dashboard use HTTPS would be preferred here, just as a certainty that we don't leave open any hole into the opensearch interface. So I'm happy to take over the annotations from `ayekan` onto other clusters as this is the current working setup for ayekan and it's been OK on it.

Not sure if @birgitcroux has a specific opinion on having the dashboard also have TLS enabled or not.

2024-08-21 14:22 UTC, fbegyn commented on fleet/lib/opensearch-logging/clusters/logging.yaml
> +      enable: true
I'd say we await the conclussion on https://github.com/lsst-it/k8s-cookbook/pull/397#discussion_r1725144451 and close/change this according to it?

2024-08-21 14:25 UTC, fbegyn commented
I don't think any manual work is needed on the cluster to get data flowing into, given that the data sources are correctly sending data to opensearch. @birgitcroux can confirm it, but we might just need to jump into a call to see what issues you are running into on the opensearch side.

Indices/data streams will only show up when data is flowing into them, otherwise they won't be created by Opensearch.

2024-08-30 22:17 UTC, jhoblitt requested changes
I haven't looked at this in detail yet.  I moved ayekan back to the ayekan-wip namespace which had a gitrepo pointed at this branch and it is failing:

![image](https://github.com/user-attachments/assets/3ab0a5a9-8cbb-49af-99c6-61d3d357924c)

I would like the fleet errors to be resolved before I do a final review / redeployment testing on this branch.

2024-10-28 16:32 UTC, jhoblitt commented
Rebased on current master. This PR has problems that will be fixed in a separate PR, if we keep opensearch.

2024-10-28 16:32 UTC, merged