IT-5135/cp v1.27.12 rancher1-1
lsst-it/k8s-cookbook pull request #420
Opened 2024-05-20 19:01 UTC by cbarria

bump k8s version on all cp clusters to v1.27.12

2024-05-20 19:18 UTC, jhoblitt requested changes
The rancher.cp rancher `values.yaml` should be updated to remove the psp config (as it isn't relevant for k8s > 1.25).

The PR title also needs to be updated.

2024-05-20 19:19 UTC, jhoblitt commented on lukay/rke/cluster.yml
The commit message for lukay is capitalized when it shouldn't be.

2024-05-20 20:22 UTC, cbarria commented on lukay/rke/cluster.yml
fixed 👍🏻

2024-05-21 21:23 UTC, jhoblitt approved these changes
LGTM.

2024-05-22 16:13 UTC, merged