(antu) add production host up/down alert config
lsst-it/k8s-cookbook pull request #502
Opened 2024-06-18 02:03 UTC by jhoblitt

Based on #498

2024-06-18 17:00 UTC, fbegyn requested changes
Aside from the incorrect YAML format in the `/rules` directory, this seems OK

2024-06-18 17:03 UTC, jhoblitt commented on fleet/lib/prometheus-alerts/rules/prometheusrule-net.yaml
> +spec:
It wasn't intentionally committed without modification to work with the template.  What's odd is that this is actually live and working.  I will fix it.

2024-06-21 15:13 UTC, fbegyn approved these changes
As with some other PR, without a `receiver: ",slack,"` like label, this alerts will just be blackholed by the alertmanager. Otherwise these alerts like fine now.

2024-06-21 16:13 UTC, jhoblitt commented
> As with some other PR, without a `receiver: ",slack,"` like label, this alerts will just be blackholed by the alertmanager. Otherwise these alerts like fine now.

At the moment, the label `prod` is being matched for sending to squadcast.

2024-06-21 16:13 UTC, merged