(fleet/kuma) deploy a temporary kuma dev monitoring instance
lsst-it/k8s-cookbook pull request #633
Opened 2024-10-18 14:59 UTC by dtapiacl

This will be "temporary", yes i know we don't like to use that word around here.

2024-10-18 15:17 UTC, jhoblitt requested changes

2024-10-18 15:18 UTC, jhoblitt reviewed
When looking at the repo history, this commit message wouldn't be very helpful:
![image](https://github.com/user-attachments/assets/d8aa9d80-6671-40ce-9f97-caadbe23f174)

2024-10-18 15:39 UTC, dtapiacl commented on fleet/lib/kuma/values.yaml
> +    kubernetes.io/ingress.class: nginx
I think it does based on the source code:

https://github.com/dirsigler/uptime-kuma-helm/blob/1e70146809f3f651a00af065a734491facb2caa2/charts/uptime-kuma/templates/ingress.yaml#L30

I will update the code to use that instead.

2024-10-18 15:45 UTC, dtapiacl commented on fleet/lib/kuma/values.yaml
> +      proxy_ssl_verify off;
Ok, I will clean up line 7.

2024-10-18 17:50 UTC, dtapiacl commented on fleet/lib/kuma/values.yaml
> +  existingClaim: ""
I would prefer so if possible, as i did not find a persistence key on the values chart.

2024-10-21 11:59 UTC, dtapiacl commented on fleet/lib/kuma/values.yaml
> +    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
Probably not. From what I read, I'm going to remove this value as it's optional.

2024-10-21 14:42 UTC, dtapiacl commented on fleet/lib/kuma/values.yaml
> +    kubernetes.io/ingress.class: nginx
Had to update the code as values uses `className:` now its working.

2024-10-21 15:08 UTC, dtapiacl commented
> When looking at the repo history, this commit message wouldn't be very helpful: ![image](https://private-user-images.githubusercontent.com/948901/377922559-d8aa9d80-6671-40ce-9f97-caadbe23f174.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MjM1MDksIm5iZiI6MTcyOTUyMzIwOSwicGF0aCI6Ii85NDg5MDEvMzc3OTIyNTU5LWQ4YWE5ZDgwLTY2NzEtNDBjZS05Zjk3LWNhYWRiZTIzZjE3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQxNTA2NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDY5ZjRkODU1NTg4NDRiODFlMDZlMzEyNTQzMDc5YjZiMzNmZDU2YmY4MWY0MzZkZmQ3YzAwMWZmYzcwM2I1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.A8SWG5-k_mTf7vvpkTA8vitvA_GZ7Bgil9pS5uh5O-Q)

I squashed on to main commit.

2024-10-21 15:34 UTC, jhoblitt approved these changes

2024-10-21 16:26 UTC, gseriche approved these changes

2024-10-21 16:58 UTC, merged