(lfa/policies) add Lifecycle 30 days to LFA in the TTS and BTS
lsst-it/k8s-cookbook pull request #647
Opened 2024-10-25 19:11 UTC by cbarria

this lifecycle were discuss with Michael extensively (and also tested) in the TTS, no prefix is needed as `The LFA is not an Archiver`. the summit will be set higher but not until the replication is stable because the information there is relevant. (becoming an archiver)

2024-10-28 17:12 UTC, jhoblitt requested changes

2024-10-28 18:20 UTC, cbarria commented on konkong/rook-ceph/s3/lfa-ls-lifecycle.json
> +        }
this is awesome, i will add that, thanks.

2024-11-04 16:28 UTC, jhoblitt approved these changes
LGTM. Thank you for incorporating the bucket lifecycle.

2024-11-04 16:29 UTC, gseriche approved these changes
lgtm

2024-11-06 14:17 UTC, merged